services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rust_pass
      MYSQL_DATABASE: "rust_db"
    ports:
      - 3306:3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  backend:
    build:
      context: ./backend
      target: final
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    restart: always