services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rust_pass
      MYSQL_DATABASE: "rust_db"
    ports:
      - 3306:3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  backend:
    build:
      context: ./backend
      target: final
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
  frontend:
    build:
      context: ./frontend
      target: prod
    env_file:
      - .env
    ports:
      - 5173:5173
    depends_on:
      - backend
    restart: always
