services:
  backend:
    build:
      context: ./backend
      target: final
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rust_pass
      MYSQL_DATABASE: "rust_db"
    ports:
      - 3306:3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
